<template>
  <div class="container">
    <div class="header">
      <h1>Terms and Conditions</h1>
      <div class="last-updated">Last Updated: January 31, 2026</div>
    </div>

    <p>Welcome to <strong>Chefpilot</strong>. These Terms and Conditions ("Terms") govern your access to and use of the Chefpilot mobile application, website, and related services (collectively, the "Service"). By creating an account or using the Service, you agree to be bound by these Terms.</p>

    <h3>1. Acceptance of Terms</h3>
    <p>By using Chefpilot, you confirm that you are at least 18 years of age (or the age of majority in your jurisdiction) and possess the legal capacity to enter into these Terms. If you are using the Service on behalf of an entity, you represent that you have the authority to bind that entity.</p>

    <h3>2. The Service</h3>
    <p>Chefpilot provides AI-powered kitchen inventory management and recipe suggestions.</p>
    <ul>
      <li><strong>AI Suggestions:</strong> You acknowledge that recipes and daily suggestions are generated by artificial intelligence. While we strive for accuracy, Chefpilot does not guarantee the quality, taste, or success of any recipe.</li>
      <li><strong>Morning Updates:</strong> Automatic daily suggestions are based on the inventory data provided by you. The Service depends on your accurate input of ingredients and expiration dates.</li>
    </ul>

    <h3>3. Food Safety and Allergy Disclaimer</h3>
    <div class="disclaimer-box">
      <strong>YOUR SAFETY IS YOUR RESPONSIBILITY.</strong>
    </div>
    <ul>
      <li><strong>Allergens:</strong> Chefpilot may suggest recipes containing ingredients to which you or your household members are allergic. Always cross-check ingredients against your specific dietary needs.</li>
      <li><strong>Food Quality:</strong> Chefpilot suggests recipes based on inventory data you provide. We cannot verify the actual freshness, storage conditions, or safety of your physical ingredients. Always inspect food for spoilage before consumption.</li>
      <li><strong>Medical Advice:</strong> Chefpilot is not a medical or nutritional advisory service. Consult a professional before starting any specific diet.</li>
    </ul>

    <h3>4. User Accounts</h3>
    <ul>
      <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
      <li>You agree to provide accurate and current information.</li>
      <li>Chefpilot reserves the right to suspend or terminate accounts that provide false information or violate these Terms.</li>
    </ul>

    <h3>5. Subscriptions and Payments</h3>
    <p>If you opt for a premium version of the Service:</p>
    <ul>
      <li><strong>Billing:</strong> Payments will be processed through your respective App Store (Apple App Store or Google Play Store).</li>
      <li><strong>Cancellations:</strong> You may cancel your subscription at any time through your store settings. Refunds are subject to the policies of the respective App Store.</li>
      <li><strong>Price Changes:</strong> We reserve the right to modify subscription fees upon reasonable notice.</li>
    </ul>

    <h3>6. Intellectual Property</h3>
    <ul>
      <li><strong>Our Content:</strong> All software, design, text, and logos (including the Chefpilot brand and "AI Sous-Chef" concepts) are the property of Chefpilot or its licensors.</li>
      <li><strong>User Content:</strong> By uploading inventory data or photos to the Service, you grant Chefpilot a non-exclusive, royalty-free license to use that data to improve our AI models and provide the Service to you.</li>
    </ul>

    <h3>7. Prohibited Conduct</h3>
    <p>You agree not to:</p>
    <ul>
      <li>Use the Service for any illegal purpose.</li>
      <li>Attempt to reverse-engineer or "scrape" the AI recipe database.</li>
      <li>Input malicious code or interfere with the Service’s security features.</li>
    </ul>

    <h3>8. Limitation of Liability</h3>
    <p>To the maximum extent permitted by law, Chefpilot shall not be liable for any indirect, incidental, or consequential damages, including but not limited to food poisoning, allergic reactions, or loss of data resulting from your use of the Service. Our total liability shall not exceed the amount you paid us in the past six months.</p>

    <h3>9. Modifications to Terms</h3>
    <p>We may update these Terms from time to time. We will notify you of significant changes via email or an in-app notification. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>

    <h3>10. Governing Law</h3>
    <p>These Terms are governed by the laws of the jurisdiction in which Chefpilot is incorporated, without regard to conflict of law principles.</p>

    <div class="contact-info">
      <strong>Contact Us</strong>
      <p>If you have any questions about these Terms, please contact us at:</p>
      <p><strong>Email:</strong> <a href="mailto:hello@chefpilot.live">hello@chefpilot.live</a></p>
      <p><strong>Website:</strong> <a href="https://www.chefpilot.live" target="_blank">www.chefpilot.live</a></p>
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent} from 'vue'

export default defineComponent({
  name: "terms"
})
</script>

<style scoped>
:root {
  --primary-green: #2D5A27;
  --bg-sage: #F9FBF9;
  --text-dark: #1a1a1a;
  --text-muted: #4b5563;
  --border-color: #e5e7eb;
}

body {
  font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
  line-height: 1.6;
  color: var(--text-dark);
  background-color: var(--bg-sage);
  margin: 0;
  padding: 0;
}

.container {
  max-width: 800px;
  margin: auto;
  background: #ffffff;
  padding: 60px;
  padding-top: 10em;
  border-radius: 12px;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03);
  border: 1px solid var(--border-color);
}

.header {
  border-bottom: 2px solid var(--bg-sage);
  margin-bottom: 30px;
  padding-bottom: 20px;
}

h1 {
  color: var(--primary-green);
  font-size: 2.25rem;
  margin: 0 0 10px 0;
  font-weight: 800;
}

.last-updated {
  color: var(--text-muted);
  font-size: 0.9rem;
  font-style: italic;
}

h3 {
  color: var(--primary-green);
  font-size: 1.4rem;
  margin-top: 35px;
  margin-bottom: 15px;
  border-left: 4px solid var(--primary-green);
  padding-left: 15px;
}

p {
  margin-bottom: 1.25rem;
}

ul {
  margin-bottom: 1.5rem;
  padding-left: 1.5rem;
}

li {
  margin-bottom: 0.75rem;
}

strong {
  color: var(--text-dark);
}

.disclaimer-box {
  background-color: #fffbeb;
  border-left: 4px solid #f59e0b;
  padding: 20px;
  margin: 25px 0;
  font-weight: 500;
}

.contact-info {
  background-color: var(--bg-sage);
  padding: 30px;
  border-radius: 8px;
  margin-top: 50px;
  border: 1px dashed var(--primary-green);
}

.contact-info p {
  margin: 5px 0;
}

a {
  color: var(--primary-green);
  text-decoration: none;
  font-weight: 600;
}

a:hover {
  text-decoration: underline;
}

@media (max-width: 640px) {
  .container {
    margin: 0;
    padding: 30px 20px;
    padding-top: 10em;
    border-radius: 0;
  }
  h1 { font-size: 1.75rem; }
}
</style>